//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_boot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int O_id { get; set; }
        public int O_product { get; set; }
        public int O_User { get; set; }
        public int O_invoice { get; set; }
        public Nullable<System.DateTime> O_date { get; set; }
        public Nullable<int> O_quantity { get; set; }
        public Nullable<double> O_unit_price { get; set; }
        public Nullable<double> O_bill { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
